- name: AWS SNS - Publish Topic
  uses: nothingalike/sns-publish-topic@v1.7
  
- name: Publish SNS Topic
  uses: nothingalike/sns-publish-topic@v1.6
  with:
    MESSAGE: "message"
    TOPIC_ARN: "arn:aws:sns:[your region]:[your account id]:[your topic name]"
  env:
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: AKIAQ5HJ62JQSOOAWYW5
    AWS_SECRET_ACCESS_KEY:  j+PAE3oONBlCPX7Px27gAWbcxaaRmnTccW3a6AWI
