AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template.
Resources:
  Digital1APIAuthorizerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Digital1APIAuthorizer
      CodeUri: ./Code
      Role: arn:aws:iam::062767682145:role/Kishore-lambda-layer
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 512
      Timeout: 15
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-2